--- #YAML:1.0
name:                CPAN-Testers-Common-DBUtils
version:             0.08
abstract:            Basic Database Wrapper used by CPAN Testers modules
author:
  - Barbie <barbie@cpan.org>

license:             artistic_2
distribution_type:   module
installdirs:         site

requires:
  perl:                   5.006
  Carp:                   0
  Class::Accessor::Fast:  0
  DBI:                    0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Database:         0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  CPAN::Testers::Common::DBUtils:
    file:     lib/CPAN/Testers/Common/DBUtils.pm
    version:  0.08

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
